site_name: "Tec+60: Turma de 2025"
site_description: "Site da turma de 2025 do curso de extensão Tec+60 do IFRN campus Parnamirim"
site_author: "Tec+60"
site_url: "https://tec60.github.io/turma2025/"

repo_url: "https://gitea.mange.ifrn.edu.br/tec60/turma2025/"
edit_uri: "_edit/estudantes/docs/"

theme:
    name: material
    language: pt

plugins:
    - search
    - awesome-pages


